DROP TABLE IF EXISTS user_order;
CREATE TABLE user_order(
  id VARCHAR(125) NOT NULL PRIMARY KEY,
  price BIGINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 0,
  creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);