DROP TABLE IF EXISTS pay;
CREATE TABLE pay(
  id VARCHAR(125) NOT NULL PRIMARY KEY,
  order_id VARCHAR(125) NOT NULL DEFAULT "",
  pay_id VARCHAR(123) NOT NULL DEFAULT "",
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0:no pay,1:payed',
  creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
)

