server:
  port: 8005
spring:
  datasource:
    name: campaign
    username: wusc
    password: Wusc@2017
    url: jdbc:mysql://47.94.8.65:3306/report?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver