server:
  port: 8005
spring:
  datasource:
    name: campaign
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/report?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver