from: campaign-pro master

server:
  port: 8003

spring:
  datasource:
    name: campaign
    username: wusc
    password: Wusc@2017
    url: jdbc:mysql://47.94.8.65:3306/campaign?useUnicode=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: wusc
    password: 123456
  redis:
    host: 47.94.8.65
    port: 6379
    password: 123456
    timeout: 10000

# 设置连接超时时间
ribbon:
  ConnectTimeout: 600
# 设置读取超时时间
  ReadTimeout: 6000
# 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
# 切换实例的重试次数
  MaxAutoRetriesNextServer: 2
# 对当前实例的重试次数
  MaxAutoRetries: 1

# Hystrix功能开关
feign.hystrix.enabled: true
# 设置熔断超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
# 关闭熔断功能
hystrix.command.default.execution.timeout.enabled: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.wusc.campaign.com.wusc.entrancebase.model
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: false
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
