server:
  port: 80
zuul:
  retryable: false #是否开启重试功能
  max:
    host:
      connections: 5000
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  prefix: /api
  routes:
    campaign:
      path: /campaign/**
      serviceId: campaign
      stripPrefix: true
    pay:
      path: /pay/**
      serviceId: pay
      stripPrefix: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000
  MaxAutoRetries: 4 #对当前服务的重试次数
  MaxAutoRetriesNextServer: 0 #切换相同Server的次数

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
spring:
  redis:
    host: 47.94.8.65
    port: 6379
    password: 123456
    timeout: 10000
gateway:
  allow:
   url: /api/campaign/login,/api/pay/call_back_wx,/api/pay/rpc