server:
  port: 80

zuul:
  max:
    host:
      connections: 5000
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  prefix: /api
  routes:
    campaign:
      path: /campaign/**
      serviceId: campaign
      stripPrefix: true
    pay:
      path: /pay/**
      serviceId: pay
      stripPrefix: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
spring:
  redis:
    host: 47.94.8.65
    port: 6379
    password: 123456
    timeout: 10000
gateway:
  allow:
   url: /api/campaign/login,/api/pay/call_back_wx