server:
  port: 8001
  num: 3
log:
  home: C:\Users\hasee\Desktop\logdata
  sys:
    level: info

spring:
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: wusc
      password: 123456