eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

spring:
  application:
    name: redis

server:
  port: 8004

redis:
  host: 47.94.8.65
  port: 6379
  password: 123456
  timeout: 10000
